"""Feature metadata definitions for Phase 4.3 – Feature Engineering.

Every feature generated by the GridSense AI feature pipeline is described by a
:class:`FeatureMetadata` record.  This enables:

- Automatic documentation generation.
- Feature lineage tracing (which raw columns produced which features).
- Version-controlled feature definitions.
- Validation against expected output ranges.

All metadata is written to ``reports/features/metadata/`` as JSON.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

FEATURE_SCHEMA_VERSION = "4.3.0"


@dataclass(slots=True)
class FeatureMetadata:
    """Describes a single engineered feature.

    Attributes
    ----------
    name:
        Snake-case feature column name (e.g. ``"heat_index"``).
    description:
        Human-readable description of what the feature represents.
    formula:
        Mathematical or algorithmic formula used to compute the feature.
    input_columns:
        Raw or intermediate columns required to compute this feature.
    output_type:
        Python type name of the feature value (``"float"``, ``"int"``, ``"str"``, ``"bool"``).
    category:
        High-level category (e.g. ``"time"``, ``"weather"``, ``"energy"``,
        ``"air_quality"``, ``"rolling"``, ``"lag"``, ``"statistical"``,
        ``"interaction"``).
    dependencies:
        Other feature names that must be computed before this one.
    version:
        Schema version string, defaults to :data:`FEATURE_SCHEMA_VERSION`.
    valid_min:
        Minimum expected value (used by the validator).
    valid_max:
        Maximum expected value (used by the validator).
    created_at:
        UTC ISO-8601 timestamp when the metadata record was created.
    tags:
        Optional free-form tags for grouping (e.g. ``["kpi", "dashboard"]``).
    """

    name: str
    description: str
    formula: str
    input_columns: List[str]
    output_type: str
    category: str
    dependencies: List[str] = field(default_factory=list)
    version: str = FEATURE_SCHEMA_VERSION
    valid_min: Optional[float] = None
    valid_max: Optional[float] = None
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    tags: List[str] = field(default_factory=list)


@dataclass
class FeatureReport:
    """Summary report for one feature engineering run.

    Attributes
    ----------
    dataset:
        Source dataset name.
    features_generated:
        Total number of new feature columns added.
    columns_added:
        List of feature column names added.
    rows_processed:
        Number of rows that were feature-engineered.
    execution_time_seconds:
        Wall-clock seconds for the run.
    warnings:
        Non-fatal issues encountered.
    errors:
        Fatal or near-fatal issues encountered.
    validation_summary:
        Result counts from the feature validator.
    created_at:
        UTC ISO-8601 timestamp.
    """

    dataset: str
    features_generated: int = 0
    columns_added: List[str] = field(default_factory=list)
    rows_processed: int = 0
    execution_time_seconds: float = 0.0
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    validation_summary: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


def write_feature_report(report: FeatureReport, reports_root: Path) -> Path:
    """Write a :class:`FeatureReport` atomically to ``reports/features/``.

    Parameters
    ----------
    report:
        Populated report instance.
    reports_root:
        Root directory for all reports (e.g. ``Path("reports")``).

    Returns
    -------
    Path
        Absolute path of the written JSON file.
    """
    target_dir = reports_root / "features"
    target_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    file_path = target_dir / f"{report.dataset}_{ts}.json"
    file_path.write_text(
        json.dumps(asdict(report), indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return file_path


def write_feature_metadata(
    metadata_list: List[FeatureMetadata],
    reports_root: Path,
    dataset: str,
) -> Path:
    """Write feature metadata records to ``reports/features/metadata/``.

    Parameters
    ----------
    metadata_list:
        List of :class:`FeatureMetadata` instances for this run.
    reports_root:
        Root reports directory.
    dataset:
        Dataset identifier used as subdirectory.

    Returns
    -------
    Path
        Absolute path of the written JSONL metadata file.
    """
    target_dir = reports_root / "features" / "metadata" / dataset
    target_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    file_path = target_dir / f"{ts}.jsonl"
    lines = [
        json.dumps(asdict(meta), ensure_ascii=False) for meta in metadata_list
    ]
    file_path.write_text("\n".join(lines), encoding="utf-8")
    return file_path
